{% set pyproject = load_file_data('pyproject.toml', from_recipe_dir=True) %}
{% set data = pyproject['project'] %}
{% set name = data['name'] %}
{% set python = data['requires-python'] %}
{% set version = '0.7.1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  string: py38_gdal30
  script: python setup.py install --single-version-externally-managed --record=record.txt
  include_recipe: False
  entry_points:
    - {{ name }} = {{ name }}.__main__:main

requirements:
  host:
    {% for req in pyproject['build-system'].get('requires', []) %}
    - {{ req.lower() }}
    {% endfor %}
  run:
    - python{{ python }}
    {% for dep in data.get('dependencies', []) %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - {{ name }}
    - {{ name }}.constants
    - {{ name }}.basetools
    - {{ name }}.gistools
    - {{ name }}.preproc
  commands:
    - {{ name }} help

outputs:
  - name: {{ name }}

about:
  description: {{ data.get('description') }}
  license: MIT
  license_file: LICENSE.txt